apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
  labels:
    app: multi-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
          name: nginx-port
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
          name: multi-port
        env:
        - name: HTTP_PORT
          value: "8080"
