apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
   index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Это заголовок</title> # ИЗМЕНИТЕ: Заголовок страницы
    </head>
    <body>
      <h1>Привет от Kubernetes! Этот index.html взят из configmap </h1> # ДОБАВЬТЕ: Свой контент страницы
    </body>
    </html>
