# inventory.tpl
# Ansible inventory file generated by Terraform
# Generated at: ${timestamp()}

# =============================================================================
# ALL HOSTS (group all)
# =============================================================================
[all]
%{ for server in all_servers ~}
${server.name} ansible_host=${server.host} fqdn=${server.fqdn}
%{ endfor ~}

# =============================================================================
# WEBSERVERS GROUP
# =============================================================================
[webservers]
%{ for server in web_servers ~}
${server.name} ansible_host=${server.host} fqdn=${server.fqdn}
%{ endfor ~}

# =============================================================================
# DATABASES GROUP
# =============================================================================
[databases]
%{ for server in database_servers ~}
${server.name} ansible_host=${server.host} fqdn=${server.fqdn}
%{ endfor ~}

# =============================================================================
# STORAGE GROUP
# =============================================================================
[storage]
%{ for server in storage_server ~}
${server.name} ansible_host=${server.host} fqdn=${server.fqdn}
%{ endfor ~}

# =============================================================================
# GROUP VARIABLES
# =============================================================================

# Общие переменные для всех групп
[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Переменные для веб-серверов
[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
http_port=80

# Переменные для баз данных
[databases:vars]
ansible_python_interpreter=/usr/bin/python3
db_port=5432

# Переменные для storage
[storage:vars]
ansible_python_interpreter=/usr/bin/python3
storage_path=/mnt/storage

# =============================================================================
# CHILDREN GROUPS (для расширенных сценариев)
# =============================================================================

# Группа, объединяющая все сервера с публичным доступом
[public:children]
webservers
storage

# Группа, объединяющая все сервера с внутренним доступом
[private:children]
databases