apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
spec:
  selector:
    app: web-app
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80          
      targetPort: 80    

    - name: multitool-port
      protocol: TCP
      port: 1180        
      targetPort: 1180  
